### ISSUE TITLE
Suggestion: creation of a Discord.

### ISSUE THREAD

**Issue by jluiiizz** [joebew42/twitch#19]
I don't know if you know Discord Joe, but if not, its a program used by a lot of streamers (Most gaming streamers, but i already saw some Creative/Programming streamers with their servers on Discord) to communicate and interact with viewers and subscribers. On Discord you can use text chat or voice chat to speak with other people. You can create a lot of channels (look like rooms), and each one with a specific function, for example, one channel focused on Elixir, and other channel focused on Good Practices, and other focused on your actual project that you are working, and people will interacting in this chats and sending and receiving knowledge. Its free, and i think that he can make the interaction better.

Link to Discord site: https://discordapp.com/

**Comment by workgena** [comment]
Most of programmers uses Telegram more often.
For example, my colleagues even don't know about discord 😞 
Joe already has Telegram. It will be not very convenient to have two chats(synchronization).

**Comment by joebew42** [comment]
Hello @jluiiizz thank you for submitting this proposal. As I said during the live session of yesterday I already know Discord, I see that a lot of streamers make use of it. I think it could be a useful tool to enhance the interaction with the viewers during the live session.

I think that instead to use Discord as an alternative chat, just because we already have the Twitch chat and as @workgena noticed, we have a Telegram Official channel too, I would like to use Discord to bring viewers to voice chat with me, by hosting:

- Live pair programming session on opensource projects
- Interviews with other software developers who wants to share their experiences (e.g. tools, programming language, practices, workplaces, etc ...)

What do you think?

**Comment by joebew42** [comment]
Hello @jluiiizz and @workgena , as I announed in the Telegram channel, during these days I find some time to create and try a Discord server for the Twitch channel. You can join it at [this link](https://discord.gg/B7HS2AT). See you there, and tomorrow for the normal streaming schedule :rocket:
